Repository datalab-greta/Projet_4_Alex_Nico_Marceline, pull requests merged in 2019-10, with the labels that each got.

#1 Scrapping_FUN_MOOC_v1.1
  Scrapping_json_Alpha.py
Labels: Python, Scraping

#5 Envoi du dossier Alex
  Git_Alex/Scrapping_json_Alex.py
Labels: FUN MOOC, Python, Scraping

#6 Selenuim
  testselenium.py
  testselenium_v1.1.py
Labels: FUN MOOC, Python

#3 Ajout script de Nico v1.2
  Scrapping_json_Nico.py
Labels: FUN MOOC, Python, Scraping

#9 ConfigParser avec quelques tests d'analyses...
  CONFIGPARSER.R
Labels: Analyse, FUN MOOC, Mongo, R

#10 Exploration des threads V1.2
  Selenium_exploration_every_thread.py
Labels: FUN MOOC, Loop, Python, Scraping, Selenium

#7 Mise à jour fichier Alex avec Sélénium
  Git_Alex/Scrapping_json_Alex.py
  Git_Alex/Selenium_AlexV.1.2.py
  Git_Alex/Selenium_AlexV.1.3.py
  Git_Alex/Selenium_AlexV.1.5.py
Labels: FUN MOOC, Selenium, enhancement

#12 Mongo to postgre nico aplatyrv3.4
  APLATYR_V3.4.py
  CONFIGPARSER.R
  Git_Alex/Scrapping_json_Alex.py
  Git_Alex/Selenium_AlexV.1.2.py
  Git_Alex/Selenium_AlexV.1.3.py
  Git_Alex/Selenium_AlexV.1.5.py
  Scrapping_json_Nico.py
Labels: FUN MOOC, Mongo, Postgre, Python

#13 Ajout de la connection à la base postgre
  Connect_pers.R
Labels: Postgre, R

#14 MongoToPostgreSQL
  APLATYR_VERSION_TITLE.py
Labels: FUN MOOC, Mongo, Postgre, Python

#15 Nouvelle version du script
  Connect_pers.R
  Presentation.Rmd
  Presentation_final.html
Labels: Dataviz, R

#11 A TESTER
  Selenium_AlexV.1.5(test_boucle).py
  Selenium_AlexV.1.6.py
  Selenium_AlexV.1.7(version_finale).py
Labels: Python, Selenium, help wanted

#17 MAJ pour fin de projet
  Git_Alex/Scrapping_json_Alex.py
  Git_Alex/Selenium_AlexV.1.2.py
  Git_Alex/Selenium_AlexV.1.3.py
  Git_Alex/Selenium_AlexV.1.5.py
  Graphiques.R
Labels: enhancement
